export const STORE_ITEMS = "STORE_ITEMS";
export const FILTERED_ITEMS = "FILTERED_ITEMS";
export const FILTER_ALL = "FILTER_ALL";
export const ADD_TO_COMPARISON = "ADD_TO_COMPARISON";
export const REMOVE_FROM_COMPARISON = "REMOVE_FROM_COMPARISON";
